JobCards/Controllers/HomeController.cs
using JobCards.Security;
using System.Web.Mvc;
using JobCards.Models.EntityManager;
using System.Linq;
using Microsoft.AspNet.Identity;

namespace JobCards.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Welcome()
        {
            var manager = new JobCardManager();
            var userID = User.Identity.GetUserId<int>();
            var view = manager.GetLastJobCards(5, manager.GetUserID(User.Identity.Name), true);
            return View(view);
        }

        public ActionResult UnAuthorized()
        {
            return View();
        }
    }
}

JobCards/Controllers/JobCardController.cs
using JobCards.Models.EntityManager;
using JobCards.Models.ViewModel;
using JobCards.Security;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace JobCards.Controllers
{
    public class JobCardController : Controller
    {
        [AuthorizeRoles("Admin", "User")]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                JobCardManager manager = new JobCardManager();
                List<JobCardView> view = manager.GetAllJobCards(true);
                return View(view);
            }

            return View();
        }

        [AuthorizeRoles("User")]
        public ActionResult Create()
        {
            JobCardManager manager = new JobCardManager();

            var jobCardView = new JobCardView()
            {
                Customers = manager.GetAllCustomers(false),
                Designers = manager.GetAllDesigners(false),
                JobTypes = manager.GetAllJobTypes(false),
                Materials = manager.GetAllMaterials(false)
            };

            return View(jobCardView);
        }

        [AuthorizeRoles("Admin")]
        public ActionResult CreateAdmin()
        {
            JobCardManager manager = new JobCardManager();

            var jobCardView = new JobCardAdminView()
            {
                Customers = manager.GetAllCustomers(false),
                Designers = manager.GetAllDesigners(false),
                JobTypes = manager.GetAllJobTypes(false),
                Materials = manager.GetAllMaterials(false)
            };

            return View(jobCardView);
        }

        [HttpPost]
        public ActionResult Create(JobCardView jobCardView)
        {
            if (ModelState.IsValid)
            {
                if (jobCardView.CustomerID == null ||
                    jobCardView.DesignerID == null ||
                    jobCardView.JobTypeID == null ||
                    jobCardView.MaterialID == null)
                {
                    return CreateAdmin();
                }

                JobCardManager manager = new JobCardManager();
                jobCardView.CreatedID = manager.GetUserID(User.Identity.Name);
                jobCardView.CreatedDate = DateTime.Now;
                manager.CreateJobCard(jobCardView);

                return RedirectToAction("Index");
            }

            return Create();
        }

        [HttpPost]
        public ActionResult CreateAdmin(JobCardAdminView jobCardView)
        {
            if (ModelState.IsValid)
            {
                if (jobCardView.CustomerID == null ||
                    jobCardView.DesignerID == null ||
                    jobCardView.JobTypeID == null ||
                    jobCardView.MaterialID == null)
                {
                    return CreateAdmin();
                }

                JobCardManager manager = new JobCardManager();
                jobCardView.CreatedID = manager.GetUserID(User.Identity.Name);
                jobCardView.CreatedDate = DateTime.Now;
                manager.CreateJobCard(jobCardView);

                return RedirectToAction("Index");
            }

            return CreateAdmin();
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Details(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult UVPrinted(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult UVPrintedResult(JobCardView jobCard)
        {
            JobCardManager manager = new JobCardManager();
            manager.SetUVPrinted(User.Identity.Name, jobCard);
            return RedirectToAction("Index");
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Application(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult ApplicationResult(JobCardView jobCard)
        {
            JobCardManager manager = new JobCardManager();
            manager.SetApplication(User.Identity.Name, jobCard);
            return RedirectToAction("Index");
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Clading(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult CladingResult(JobCardView jobCard)
        {
            JobCardManager manager = new JobCardManager();
            manager.SetClading(User.Identity.Name, jobCard);
            return RedirectToAction("Index");
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Installation(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult InstallationResult(JobCardView jobCard)
        {
            JobCardManager manager = new JobCardManager();
            manager.SetInstallation(User.Identity.Name, jobCard);
            return RedirectToAction("Index");
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Invoice(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);

            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult InvoiceResult(JobCardView jobCard)
        {
            JobCardManager manager = new JobCardManager();
            manager.SetInvoice(User.Identity.Name, jobCard);
            return RedirectToAction("Index");
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult History(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);
            jobCard.Customers = manager.GetAllCustomers(true);
            jobCard.Designers = manager.GetAllDesigners(true);
            jobCard.JobTypes = manager.GetAllJobTypes(true);
            jobCard.Materials = manager.GetAllMaterials(true);
            jobCard.Users = manager.GetAllUsers();
            return View(jobCard);
        }

        [AuthorizeRoles("Admin", "User")]
        public ActionResult Delete(int id)
        {
            JobCardManager manager = new JobCardManager();
            JobCardView jobCard = manager.GetJobCard(id, true);
            jobCard.Users = manager.GetAllUsers();
            jobCard.Customers = manager.GetAllCustomers(true);
            jobCard.Designers = manager.GetAllDesigners(true);

            return View(jobCard);
        }

        [HttpPost]
        public ActionResult Delete(JobCardView jobCard)
        {
            try
            {
                if (jobCard.JobCardID != 0)
                { 
                    JobCardManager manager = new JobCardManager();
                    manager.DeleteJobCard(jobCard);
                    return RedirectToAction("Index");
                }

                return View(jobCard);
            }
            catch
            {
                return View();
            }
        }
    }
}

JobCards/Controllers/ReportsController.cs
using JobCards.Models.EntityManager;
using JobCards.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobCards.Controllers
{
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult UVPrinting()
        {
            JobCardManager manager = new JobCardManager();
            List<JobCardView> jobCards = manager.GetUVPrintingJobCards(true);
            return View(jobCards);
        }

        public ActionResult Application()
        {
            JobCardManager manager = new JobCardManager();
            List<JobCardView> jobCards = manager.GetApplicationJobCards(true);
            return View(jobCards);
        }

        public ActionResult Clading()
        {
            JobCardManager manager = new JobCardManager();
            List<JobCardView> jobCards = manager.GetCladingJobCards(true);
            return View(jobCards);
        }

        public ActionResult Installation()
        {
            JobCardManager manager = new JobCardManager();
            List<JobCardView> jobCards = manager.GetInstallationJobCards(true);
            return View(jobCards);
        }

        public ActionResult Invoice()
        {
            JobCardManager manager = new JobCardManager();
            List<JobCardView> jobCards = manager.GetInvoiceJobCards(true);
            return View(jobCards);
        }
    }
}

JobCards/Views/Home/AdminOnly.cshtml
@{
    ViewBag.Title = "AdminOnly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>For Admin users only!</h2> 

JobCards/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DigiFusion's Job Cards</h2>
<br />
<div>
    No Account yet? @Html.ActionLink("Register Now!", "SignUp", "Account")
</div>

JobCards/Views/Home/UnAuthorized.cshtml
@{
    ViewBag.Title = "UnAuthorized";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unauthorized Access!</h2>
<p>Oops! You don't have permission to access this page.</p>

<div>
    @Html.ActionLink("Back to Main", "Welcome", "Home")
</div>  

JobCards/Views/Home/Welcome.cshtml
@model IEnumerable<JobCards.Models.ViewModel.JobCardView>
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Hi <b>@Context.User.Identity.Name</b></h2>
<br />
<h3>Your last 5 job cards</h3>
<table class="table table-striped table-condensed table-hover">
    <thead>
        <tr>
            <th>Job Number</th>
            <th>Customer</th>
            <th>Designer</th>
            <th>Job Date</th>
            <th>Quote</th>
            <th>Job Type</th>
            <th>Material</th>
            <th>Next Action</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td> @Html.DisplayFor(m => i.JobCardID)</td>
                <td> @Html.DisplayFor(m => i.Customers.Single(x => x.CustomerID == i.CustomerID).Name)</td>
                <td> @Html.DisplayFor(m => i.Designers.Single(x => x.DesignerID == i.DesignerID).Name)</td>
                <td> @Html.DisplayFor(m => i.JobDate)</td>
                <td> @Html.DisplayFor(m => i.QuoteRef)</td>
                <td> @Html.DisplayFor(m => i.JobTypes.Single(x => x.JobTypeID == i.JobTypeID).Name)</td>
                <td> @Html.DisplayFor(m => i.Materials.Single(x => x.MaterialID == i.MaterialID).Name)</td>
                
                @switch (i.TaskStep)
                {
                    case JobCards.Models.ViewModel.TaskStep.Created:
                        <td>@Html.ActionLink("UV Printing", "UVPrinted", "JobCard" , new { id = i.JobCardID }, new { })</td>
                        break;
                    case JobCards.Models.ViewModel.TaskStep.UVPrint:
                        <td>@Html.ActionLink("Application", "Application", "JobCArd", new { id = i.JobCardID }, new { })</td>
                        break;
                    case JobCards.Models.ViewModel.TaskStep.Application:
                        <td>@Html.ActionLink("Clading", "Clading", "JobCard", new { id = i.JobCardID }, new { })</td>
                        break;
                    case JobCards.Models.ViewModel.TaskStep.Clading:
                        <td>@Html.ActionLink("Installation", "Installation", "JobCard", new { id = i.JobCardID }, new { })</td>
                        break;
                    case JobCards.Models.ViewModel.TaskStep.Install:
                        <td>@Html.ActionLink("Invoicing", "Invoice", "JobCard", new { id = i.JobCardID }, new { })</td>
                        break;
                    default:
                        <td>@Html.ActionLink("Completed", "History", "JobCard", new { id = i.JobCardID }, new { })</td>
                        break;
                }

                @if (Context.User.IsInRole("Admin"))
                {
                    <td>@Html.ActionLink("Details","History","JobCard", new { id = i.JobCardID }, new { })</td>
                    <td>@Html.ActionLink("Delete", "Delete", "JobCard", new { id = i.JobCardID }, new { })</td>
                }
                else
                {
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>
<br />
<br />
<h3>Reports</h3>
<br />
<input type="button" value="UV Printing" onclick="location.href='@Url.Action("UVPrinting", "Reports")'" />
&nbsp;
<input type="button" value="Application" onclick="location.href='@Url.Action("Application", "Reports")'" />
&nbsp;
<input type="button" value="Clading" onclick="location.href='@Url.Action("Clading", "Reports")'" />
&nbsp;
<input type="button" value="Installation" onclick="location.href='@Url.Action("Installation", "Reports")'" />
&nbsp;
<input type="button" value="Invoice" onclick="location.href='@Url.Action("Invoice", "Reports")'" />